name: Auto Assign Issues

on:
  issues:
    types: [ opened ]

jobs:
  assignAuthor:
    if: github.actor != 'dependabot[bot]'

    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        uses: technote-space/assign-author@v1