name: Release Drafter
on:
  push:
    # 해당 브랜치에 푸쉬될 때 action 이 실행된다.
    branches:
      - master
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: actions-ecosystem/action-create-comment
        uses: actions-ecosystem/action-create-comment@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
        
      - name: release-drafter/release-drafter
        if: steps.get-merged-pull-request.outputs.labels != ''
        uses: release-drafter/release-drafter@v5
        # (Optional)
        # workflow 에서 여러 구성이 필요할 때 config-name 에 오버라이드 해줍니다.
        # 반드시 .github/ 에 위치해야합니다.
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
